# Generated by Django 4.2.7 on 2023-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeapp", "0002_master_data_course_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="district",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="master_data",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="master_data",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="master_data",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="state",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
