# Generated by Django 4.2.7 on 2023-11-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="installment_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
