# Generated by Django 4.2.7 on 2023-11-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="amount",
        ),
    ]
