# Generated by Django 4.2.7 on 2023-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_student_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
